### ISSUE TITLE
Update to use "rum" too?

### ISSUE THREAD

**Issue by hansgru** [tonsky/datascript-todo#1]
Please update this example to also use your other framework `rum`.

This way `rum` will have a better example too.

Thank you.

**Comment by tonsky** [comment]
Want to do a PR?

**Comment by clifford** [comment]
I had ported 'datascript-todo' to rum back in Jan. Have just created a pull
request if you're interested

**Comment by tonsky** [comment]
Updated to latest CLJS, DataScript and Rum

**Comment by tonsky** [comment]
@hansgru also updated https://github.com/tonsky/datascript-chat

**Comment by hansgru** [comment]
Nice, thank you :).
