### ISSUE TITLE
Replicating your LightTable workflow

### ISSUE THREAD

**Issue by JakePi3** [tonsky/datascript-todo#4]
I watched your vimeo presentation where you were able to evaluate expressions in LightTable at the same time as working with an external browser.

I struggled with it for a few hours but I think I've figured out some of the gotchas and hopefully this will help someone else out..

First, a clean installation of LightTable still uses the 0.1.0 Clojure plugin, which has to be manually updated (0.2.0 latest at this time).  This was causing all kinds of errors during evaluation in the LightTable UI.

Second, the top-level :cljsbuild option takes precedence over the dev profile in project.clj (when invoked with "lein cljsbuild once"), which has advanced optimizations turned on by default.  This means LightTable cannot find the goog namespace. Setting an output-dir and changing optimizations to none cleared that up for me but probably it will also work with "lein with-profile dev cljsbuild once"

I'm not sure if you were explicitly invoking the dev profile or whether you had some pre-wired defaults in your presentation that none of this came up, but hopefully you can just modify your README to reflect these requirements, probably no changes even necessary.

**Comment by tonsky** [comment]
Can you convert that to PR maybe?

**Comment by JakePi3** [comment]
Done.. Turns out no code changes were necessary.. The LightTable problems were solved by the plugin update and I had ongoing headaches because I didn't read closely.
